-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 20:38:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grabify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grabify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grabify` DEFAULT CHARACTER SET utf8 ;
USE `grabify` ;

-- -----------------------------------------------------
-- Table `grabify`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile_number` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idusers_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`business` (
  `business_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `contact_number` INT NOT NULL,
  PRIMARY KEY (`business_id`),
  UNIQUE INDEX `business_id_UNIQUE` (`business_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `business_business_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) ,
  INDEX `fk_product_business1_idx` (`business_business_id` ASC) ,
  CONSTRAINT `fk_product_business1`
    FOREIGN KEY (`business_business_id`)
    REFERENCES `grabify`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `timestamp` DATETIME NULL,
  `users_user_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  `business_business_id` INT NOT NULL,
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `review_id_UNIQUE` (`review_id` ASC) ,
  INDEX `fk_review_users_idx` (`users_user_id` ASC) ,
  INDEX `fk_review_product1_idx` (`product_product_id` ASC) ,
  INDEX `fk_review_business1_idx` (`business_business_id` ASC) ,
  CONSTRAINT `fk_review_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `grabify`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `grabify`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_business1`
    FOREIGN KEY (`business_business_id`)
    REFERENCES `grabify`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `users_user_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC) ,
  INDEX `fk_booking_users1_idx` (`users_user_id` ASC) ,
  INDEX `fk_booking_product1_idx` (`product_product_id` ASC) ,
  CONSTRAINT `fk_booking_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `grabify`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `grabify`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`favorite` (
  `fav_id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`fav_id`),
  UNIQUE INDEX `fav_id_UNIQUE` (`fav_id` ASC) ,
  INDEX `fk_favorite_users1_idx` (`users_user_id` ASC) ,
  INDEX `fk_favorite_product1_idx` (`product_product_id` ASC) ,
  CONSTRAINT `fk_favorite_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `grabify`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `grabify`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grabify`.`payment_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grabify`.`payment_info` (
  `payment_info_id` INT NOT NULL AUTO_INCREMENT,
  `Card_name` VARCHAR(64) NOT NULL,
  `Card_number` INT(16) NOT NULL,
  `expiry` VARCHAR(5) NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`payment_info_id`),
  UNIQUE INDEX `payment_info_id_UNIQUE` (`payment_info_id` ASC) ,
  INDEX `fk_payment_info_users1_idx` (`users_user_id` ASC) ,
  CONSTRAINT `fk_payment_info_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `grabify`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
